exclude: generated
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/cmhughes/latexindent.pl.git
  rev: V3.24.1
  hooks:
  - id: latexindent
    args: [-l, -s, -m, -wd]
